import type { LabelStore } from "./LabelStore.js";

// ─── ExtractorBundler: make the shipped extractor self-contained ─────────────
// The synth loop writes import-free candidates: `extract(text, store)` reading
// from an ambient `store`. That raw artifact is NOT portable on its own.
//
// At ship time we bundle the champion into ONE file that carries its own data:
//   1. an inlined, dependency-free LabelStore class,
//   2. the train-only knowledge serialized as a JSON literal,
//   3. a module-level `__store` built from it, used as the default `store` arg.
//
// The author's `extract` body is kept verbatim; we sanitize it (drop any stray
// imports / LabelStore type redefinitions the model emitted despite the contract)
// and default the `store` param to the bundled `__store`. So both `extract(text)`
// (standalone) and `extract(text, store)` (build loop, `distill run`) keep working.

export class ExtractorBundler {
  /**
   * Wrap a generated extractor `source` into a self-contained module.
   * `store` is the train-only LabelStore the champion was built against.
   */
  static bundle(source: string, store: LabelStore): string {
    const body = ExtractorBundler.sanitize(source);
    const dataLiteral = JSON.stringify(store.toData());

    return `${HEADER}

${INLINE_LABELSTORE}

// ─── Bundled train-only knowledge (do not edit) ──────────────────────────────
const __labelStoreData: LabelStoreData = ${dataLiteral};
const __store = LabelStore.fromData(__labelStoreData);

${body}
`;
  }

  /**
   * Make the author body safe to concatenate after the inlined LabelStore:
   *  - drop ALL `import ...` lines (the contract forbids imports; we inline deps),
   *  - drop any `interface LabelStore {...}` / `type LabelStore = ...` the model
   *    redefined (would collide with the inlined class),
   *  - default the exported `extract`'s `store` param to `__store`, whether it's
   *    typed (`store: LabelStore`), untyped (`store`), or already defaulted, so
   *    `extract(text)` runs standalone.
   */
  private static sanitize(source: string): string {
    let out = source.replace(/^\s*import\b.*$/gm, "");

    // Drop a redefined LabelStore type (interface or type alias).
    out = out.replace(
      /^\s*(?:export\s+)?interface\s+LabelStore\b[\s\S]*?\n\}\s*$/gm,
      "",
    );
    out = out.replace(/^\s*(?:export\s+)?type\s+LabelStore\b[^\n]*$/gm, "");

    // Default the `store` parameter of the exported extract().
    // 1) typed: `store: LabelStore` / `store: LabelStore = x` → `store: LabelStore = __store`
    if (/\bstore\s*:\s*LabelStore\b/.test(out)) {
      out = out.replace(
        /(\bstore\s*:\s*LabelStore)(\s*=\s*[^,)]+)?/,
        "store: LabelStore = __store",
      );
    } else {
      // 2) untyped or `: any` etc. inside the extract signature → add `= __store`.
      out = out.replace(
        /(export\s+function\s+extract\s*\([^)]*?\bstore\b[^,)=]*)(\s*=\s*[^,)]+)?(\s*[,)])/,
        "$1 = __store$3",
      );
    }

    return out.trimStart();
  }
}

const HEADER = `// AUTO-GENERATED by distill - self-contained extractor. Do not edit by hand.
// This file bundles its own train-only knowledge; it has no runtime deps and
// can be copied anywhere. Call extract(text) to use it.`;

// A trimmed, dependency-free copy of LabelStore: only the lookup surface the
// generated code uses, plus restore-from-data. Kept in sync with LabelStore.ts.
const INLINE_LABELSTORE = `interface LabelStoreData {
  vocab: [string, string[]][];
  prevTokenTag: [string, [string, number][]][];
  suffixTag: [string, [string, number][]][];
  tagSpanCount: [string, number][];
}

const __SENTINEL_BOS = "bos";

class LabelStore {
  readonly vocab: Map<string, Set<string>>;
  readonly tags: string[];
  private readonly prevTokenTag: Map<string, Map<string, number>>;
  private readonly suffixTag: Map<string, Map<string, number>>;
  private readonly tagSpanCount: Map<string, number>;

  private constructor(data: LabelStoreData) {
    this.vocab = new Map(data.vocab.map(([t, s]) => [t, new Set(s)]));
    this.prevTokenTag = new Map(data.prevTokenTag.map(([k, m]) => [k, new Map(m)]));
    this.suffixTag = new Map(data.suffixTag.map(([k, m]) => [k, new Map(m)]));
    this.tagSpanCount = new Map(data.tagSpanCount);
    this.tags = [...this.tagSpanCount.keys()].sort();
  }

  static fromData(data: LabelStoreData): LabelStore {
    return new LabelStore(data);
  }

  hasVocab(tag: string, span: string): boolean {
    return this.vocab.get(tag)?.has(span.toLowerCase().trim()) ?? false;
  }

  tagsForSpan(span: string): string[] {
    const s = span.toLowerCase().trim();
    return this.tags.filter((t) => this.vocab.get(t)?.has(s));
  }

  prevTokenTagProb(prevToken: string, tag: string): number {
    const key = prevToken ? prevToken.toLowerCase() : __SENTINEL_BOS;
    return __dist(this.prevTokenTag.get(key)).get(tag) ?? 0;
  }

  bestTagAfter(prevToken: string): { tag: string; prob: number } | null {
    const key = prevToken ? prevToken.toLowerCase() : __SENTINEL_BOS;
    return __argmax(__dist(this.prevTokenTag.get(key)));
  }

  suffixTagProb(suffixWord: string, tag: string): number {
    return __dist(this.suffixTag.get(suffixWord.toLowerCase())).get(tag) ?? 0;
  }

  bestTagForSuffix(suffixWord: string): { tag: string; prob: number } | null {
    return __argmax(__dist(this.suffixTag.get(suffixWord.toLowerCase())));
  }
}

function __dist(counts?: Map<string, number>): Map<string, number> {
  const out = new Map<string, number>();
  if (!counts) return out;
  let total = 0;
  for (const v of counts.values()) total += v;
  if (total === 0) return out;
  for (const [k, v] of counts) out.set(k, v / total);
  return out;
}

function __argmax(d: Map<string, number>): { tag: string; prob: number } | null {
  let best: { tag: string; prob: number } | null = null;
  for (const [tag, prob] of d) {
    if (!best || prob > best.prob) best = { tag, prob };
  }
  return best;
}`;
